#!/bin/bash
# Write '. buildAndroidKernel' in terminal to run
HASCONF=1
USAGE="Use \033[1mkhelp\033[0m to know more"

upcstr(){ CONFSTRING="$HOME/.qsbuild_config\n\n$QSH will used to building\nBuilder: $KBUILD_BUILD_USER@$KBUILD_BUILD_HOST"
}
kloadconf(){
. $HOME/.qsbuild_config
export QSH=$BUILDPATH
export KBUILD_BUILD_USER=$KUSER
export KBUILD_BUILD_HOST=$HOSTNAME
export PATH="$QSH/proton-clang/bin:$PATH"
upcstr
if [ $HASCONF = 1 ]; then
echo -e "Configuration loaded from $CONFSTRING\n\n$USAGE"
fi
}
if [ -f $HOME/.qsbuild_config ]; then
kloadconf
else
HASCONF=0
echo -e "# QuicksilveR build configuration\nBUILDPATH=$PWD\nKUSER=$USER\nKHOST=$HOSTNAME" > $HOME/.qsbuild_config
kloadconf
echo -e "Configuration written to $CONFSTRING\n\n$USAGE"
fi
kclone(){
if [ -d $QSH/kernel ]; then
echo "Kernel already cloned"
else
if ! git clone $KERNEL; then
echo "Cloning failed! Aborting..."
fi
fi
if [ -d $QSH/proton-clang ]; then
echo "Clang already cloned"
else
if ! git clone --depth=1 $CLANG; then
echo "Cloning failed! Aborting..."
fi
fi
}
kbuild(){
if [ -d $QSH/kernel ]; then
if [ -d $QSH/proton-clang ]; then
if
SECONDS=0
cd $QSH/kernel
make O=../out ARCH=arm64 vendor/ginkgo-perf_defconfig
make -j$(nproc --all) O=../out ARCH=arm64 CC=clang LD=ld.lld AR=llvm-ar AS=llvm-as NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- Image.gz-dtb
then
cd $QSH
if [ -f "out/arch/arm64/boot/Image.gz-dtb" ]; then
git clone -q https://github.com/ghostrider-reborn/AnyKernel3
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3
cd AnyKernel3
zip -r9 "../QuicksilveR-ginkgo-$(date '+%Y%m%d-%H%M')" * -x '*.git*' README.md *placeholder
cd ..
rm -rf AnyKernel3
echo -e "\nCompleted in $((SECONDS / 60)) minute(s) and $((SECONDS % 60)) second(s) !"
else
echo -e "\nBuild failed!"
fi
else
cd $QSH
echo -e "\nBuild failed!"
fi
else
echo "There is no proton-clang"
if ! git clone --depth=1 https://github.com/kdrag0n/proton-clang.git -b master; then
echo "Cloning failed! Aborting..."
else
kbuild
fi
fi
else
echo "There is no kernel"
if ! git clone https://github.com/ghostrider-reborn/android_kernel_xiaomi_ginkgo.git -b quartz kernel; then
echo "Cloning failed! Aborting..."
else
kbuild
fi
fi
}
khelp(){ echo -e "Usage:\n\n\033[1mkbuild\033[0m start build kernel\n\033[1mkloadconf\033[0m load build configuration from $HOME/.qsbuild_config\n\033[1mkclone\033[0m clone kernel and clang"
}
