#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
#
# Dependencies check utility

. ${0%/*}/../iutils

missing=""

for required in ${@}
do
    if ! command -v ${required} > /dev/null
    then
        missing="${missing} ${required}"
    fi
done

if [[ -n "${missing}" ]]
then
    echo -e "Missing dependencies:${missing}\n" \
            "For more information follow: https://command-not-found.com/"
    exit 1
fi
