#!/bin/sh -e
#
# Copyright (C) 2023 Maria Lisina
#
# Script utils importer. Do not execute from shell!

utils_list="deps"

for util in ${utils_list}
do
    alias "${util}"="${0%/*}/../utils/${util}"
done
