#!/bin/busybox sh
#
# Copyright (C) 2024 Maria Lisina
#
# Send JSON formatted data to Telegram bot

. ${0%/*}/../iutils

depends curl

tgbot_config="${HOME}/.config/tgbot"
default_json="${tgbot_config}/json"
config_file="${tgbot_config}/config"

if ! mkdir -p "${tgbot_config}"
then
    echo "Failed to create config directory"
    exit 1
fi

if ! mkdir -p "${default_json}"
then
    echo "Failed to create json directory"
    exit 1
fi

if [[ -f "${config_file}" ]]
then
    . "${config_file}"
else
    echo -e "token=\"\"\njson=\"\"" > "${config_file}"
    echo "Empty configuration file has been written to '${config_file}'"
    exit 0
fi

if [[ -z "${token}" ]]
then
    echo "No access token specified. See '${config_file}'"
    exit 1
fi

if [[ -z "${json}" ]]
then
    json="${default_json}"

    if ! [[ -d "${json}" ]]
    then
        echo "No json directory found. See '${config_file}'"
        exit 1
    fi
fi

if [[ -n "${1}" ]] && [[ -n "${2}" ]]
then
    curl -s \
        -X POST \
        -H "Content-Type: application/json" \
        -d "@${json}/${2}.json" \
        "https://api.telegram.org/bot${token}/${1}"
else
    echo -e "You must specify both arguments: post method and file name\n" \
            "Example: '${0} sendPhoto postQuark'\n" \
            "Where 'postQuark' is 'postQuark.json' file located in directory you" \
            "specified with 'json' variable"
    exit 1
fi
