#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
#
# Send JSON formatted data to Telegram bot

set -e

for required in curl mkdir
do
    if ! command -v ${required} > /dev/null
    then
        missing="${missing} ${required}"
    fi
done

if [ -n "${missing}" ]
then
    echo "Missing dependencies:${missing}\n" \
        "For more information follow: https://command-not-found.com/"
    exit 1
fi

tgbot_config="${HOME}/.config/tgbot"
default_json="${tgbot_config}/json"
config_file="${tgbot_config}/config"

mkdir -p "${tgbot_config}"
mkdir -p "${default_json}"

if [ -f "${config_file}" ]
then
    . "${config_file}"
else
    echo "token=\"\"\njson=\"\"" > "${config_file}"
    echo "Empty configuration file has been written to '${config_file}'"
    exit 0
fi

if [ -z "${token}" ]
then
    echo "No access token specified. See '${config_file}'"
    exit 1
fi

if [ -z "${json}" ]
then
    json="${default_json}"

    if ! [ -d "${json}" ]
    then
        echo "No json directory found. See '${config_file}'"
        exit 1
    fi
fi

if [ -n "${1}" ] && [ -n "${2}" ]
then
    if ! [ -f "${json}/${2}.json" ]
    then
        echo "No json file '${2}.json' found. See '${json}'"
        exit 1
    fi

    curl -s \
        -X POST \
        -H "Content-Type: application/json" \
        -d "@${json}/${2}.json" \
        "https://api.telegram.org/bot${token}/${1}"
else
    echo "You must specify both arguments: post method and file name\n" \
        "Example: '${0} sendPhoto postQuark'\n" \
        "Where 'postQuark' is 'postQuark.json' file located in directory you" \
        "specified with 'json' variable"
    exit 1
fi
