#!/usr/bin/env dash
#
# Copyright (C) 2024 Maria Lisina
#
# Reencode media to optimize playback in Telegram
#
# Prerequisites: ffmpeg

set -e

if [[ -z "${1}" ]]
then
    echo "No input file specified"
    exit 1
fi

if ! [[ -f "${1}" ]]
then
    echo "No input file found"
    exit 1
fi

output_file="${1%.*}_t.mp4"

if ffmpeg -i "${1}" \
    -acodec aac \
    -vcodec libx264 \
    -profile:v high \
    -pix_fmt yuv420p \
    -movflags +faststart \
    "${output_file}" -y
then
    echo "Reencoded succesfully: '${output_file}'"
else
    echo "Failed to reencode the video"
    exit 1
fi
